### ISSUE TITLE
error on trying in "import onnx_plaidml.backend"

### ISSUE THREAD

**Issue by ultimopl** [plaidml/onnx-plaidml#16]
Traceback (most recent call last):
  File "tesst.py", line 2, in <module>
    import onnx_plaidml.backend
  File "D:\Anaconda3\envs\deeplab\lib\site-packages\onnx_plaidml\backend.py", line 18, in <module>
    from onnx import onnx_pb2
ImportError: cannot import name 'onnx_pb2'

**Comment by jack-willturner** [comment]
You need to install from source, not via `pip`:

```
git clone https://github.com/plaidml/onnx-plaidml.git
cd onnx-plaidml
python setup.py build
python setup.py install
```

**Comment by tzerrell** [comment]
Thanks for the report, we're working on a release to get the pips and github back in sync. We'll update when it's out.

**Comment by ultimopl** [comment]
Many thanks!

**Comment by tzerrell** [comment]
These are now back in sync with PlaidML 0.3.5, so you'll no longer need to install from source to get this fix.
